export const ART_LIST_REQUEST = "ART_LIST_REQUEST";

export const ART_LIST_SUCCESS = "ART_LIST_SUCCESS";

export const ART_LIST_FAILED = "ART_LIST_FAILED";

export const ART_DETAILS_REQUEST = "ART_DETAILS_REQUEST";
export const ART_DETAILS_SUCCESS = "ART_DETAILS_SUCCESS";
export const ART_DETAILS_FAILED = "ART_DETAILS_FAILED";

export const ART_DELETE_REQUEST = "ART_DELETE_REQUEST";
export const ART_DELETE_SUCCESS = "ART_DELETE_SUCCESS";
export const ART_DELETE_FAILED = "ART_DELETE_FAILED";

export const ART_CREATE_REQUEST = "ART_CREATE_REQUEST";
export const ART_CREATE_SUCCESS = "ART_CREATE_SUCCESS";
export const ART_CREATE_FAILED = "ART_CREATE_FAILED";
export const ART_CREATE_RESET = "ART_CREATE_RESET";

export const ART_UPDATE_REQUEST = "ART_UPDATE_REQUEST";
export const ART_UPDATE_SUCCESS = "ART_UPDATE_SUCCESS";
export const ART_UPDATE_FAILED = "ART_UPDATE_FAILED";
export const ART_UPDATE_RESET = "ART_UPDATE_RESET";

export const ART_CREATE_REVIEW_REQUEST = "ART_CREATE_REVIEW_REQUEST";
export const ART_CREATE_REVIEW_SUCCESS = "ART_CREATE_REVIEW_SUCCESS";
export const ART_CREATE_REVIEW_FAILED = "ART_CREATE_REVIEW_FAILED";
export const ART_CREATE_REVIEW_RESET = "ART_CREATE_REVIEW_RESET";
